version: "3"
services:
  postgres:
    image: postgres:10.2
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/dev/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
